"use client";

import { motion, AnimatePresence } from "motion/react";
import { ChevronDown } from "lucide-react";
import { useState, type ReactNode } from "react";

const faqs = [
  {
    question: "What is Ginie DAML?",
    answer:
      "Ginie is an AI-powered platform that generates production-ready DAML smart contracts from plain-English descriptions. It compiles, audits, and deploys your contracts directly to the Canton Network — all in minutes.",
  },
  {
    question: "Do I need to know DAML to use Ginie?",
    answer:
      "No. Ginie's AI understands natural language contract descriptions and generates idiomatic DAML code using a curated RAG pattern library. However, experienced DAML developers can also iterate on generated code for advanced use cases.",
  },
  {
    question: "How does the security audit work?",
    answer:
      "Every contract generated by Ginie goes through an automated hybrid auditor that checks for vulnerabilities, DAML best practices, signatory/observer correctness, and Canton compliance — producing a detailed security report before deployment.",
  },
  {
    question: "What is Canton Network?",
    answer:
      "Canton is a privacy-enabled blockchain network built by Digital Asset. It uses the DAML smart contract language and supports multi-party workflows with fine-grained privacy. Ginie deploys contracts directly to Canton's ledger.",
  },
  {
    question: "Is the Sandbox plan really free?",
    answer:
      "Yes. The Sandbox plan is free forever and includes unlimited contract generation, local Canton sandbox deployment, and full security audit reports. You only pay when you're ready to deploy to DevNet or MainNet.",
  },
];

const ease = [0.23, 1, 0.32, 1] as const;

function FAQItem({
  faq,
  index,
  isOpen,
  onToggle,
}: {
  faq: (typeof faqs)[0];
  index: number;
  isOpen: boolean;
  onToggle: () => void;
}): ReactNode {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, ease, delay: index * 0.05 }}
      onClick={onToggle}
      className="cursor-pointer rounded-2xl bg-white/6 backdrop-blur-md border-t-2 border-b-2 border-white/10 p-5 shadow-sm sm:p-6"
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onToggle();
        }
      }}
      aria-expanded={isOpen}
    >
      <div className="flex w-full items-center justify-between gap-4 text-left">
        <span className="text-base font-medium sm:text-lg text-white" style={{ fontFamily: "EB Garamond, serif" }}>
          {faq.question}
        </span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3, ease }}
          className="shrink-0"
        >
          <ChevronDown className="h-5 w-5 text-white/70" />
        </motion.div>
      </div>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease }}
            className="overflow-hidden"
          >
            <p className="pt-4 text-sm leading-relaxed text-white/70 sm:text-base">
              {faq.answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export function FAQ(): ReactNode {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const handleToggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="w-full px-6 py-20 sm:py-28 bg-black">
      <div className="mx-auto max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, ease }}
          className="mb-12 text-center sm:mb-16"
        >
         
          <h2
            className="mt-3 text-4xl  tracking-tight text-white sm:text-5xl lg:text-6xl"
            style={{ fontFamily: "EB Garamond, serif", letterSpacing: '-0.02em' }}
          >
            Everything you need to know
          </h2>

          <p
            className="mx-auto mt-4 max-w-xl text-lg text-white/80 sm:text-xl"
            style={{ fontFamily: "EB Garamond, serif", fontWeight: 400 }}
          >
            Can&apos;t find the answer you&apos;re looking for? Reach out!
          </p>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
            <motion.a
              href="#"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="inline-flex items-center rounded-xl bg-foreground px-6 py-2.5 text-sm font-semibold text-background transition-colors hover:bg-foreground/90"
            >
              Launch App
            </motion.a>
            <motion.a
              href="https://docs.daml.com"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="inline-flex items-center rounded-xl border border-border bg-frame px-6 py-2.5 text-sm font-semibold text-foreground transition-colors"
            >
              View Docs
            </motion.a>
          </div>
        </motion.div>

        <div className="flex flex-col gap-3" role="list">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              faq={faq}
              index={index}
              isOpen={openIndex === index}
              onToggle={() => handleToggle(index)}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
