canton {
  features {
    enable-repair-commands = yes
  }

  participants {
    participant1 {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = ${CANTON_DB_HOST}
            serverName = ${?DATABASE_HOST}
            portNumber = ${CANTON_DB_PORT}
            portNumber = ${?DATABASE_PORT}
            databaseName = ${CANTON_DB_NAME}
            databaseName = ${?DATABASE_NAME}
            user = ${CANTON_DB_USER}
            user = ${?DATABASE_USER}
            password = ${CANTON_DB_PASSWORD}
            password = ${?DATABASE_PASSWORD}
            ssl = false
          }
        }
      }

      admin-api {
        address = "0.0.0.0"
        port = 7576
      }

      ledger-api {
        address = "0.0.0.0"
        port = 6865
      }
    }
  }

  domains {
    local {
      storage {
        type = memory
      }

      init {
        domain-parameters {
          protocol-version = 5
        }
      }

      public-api {
        address = "0.0.0.0"
        port = 7577
      }

      admin-api {
        address = "0.0.0.0"
        port = 7578
      }
    }
  }
}
