"""Generated-code branding header.

Every Daml file we ship out the door gets a small header comment that
identifies it as Canton.Ginie-generated and pins the synthesised pattern
so a human reading the .daml file later knows what plan it was built
against. This is a polish detail, not a security one \u2014 we deliberately
do NOT inject the contract spec into the file (it would be noisy and
go stale).

The header is *idempotent*: running ``prepend_brand_header`` on already
branded code is a no-op, so multi-stage post-processing (project
writer, fix loop, fallback) doesn't stack headers.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

_HEADER_MARKER = "Generated by Canton.Ginie"


def prepend_brand_header(
    code: str,
    *,
    pattern: Optional[str] = None,
    domain: Optional[str] = None,
    module_name: Optional[str] = None,
) -> str:
    """Prepend a Canton.Ginie attribution comment to a Daml source file.

    If the input already carries the marker, the original string is
    returned unchanged. The header sits *above* ``module X where`` so it
    cannot interfere with parsing.
    """
    if not code or not code.strip():
        return code
    if _HEADER_MARKER in code[:400]:
        # Already branded \u2014 don't double-stamp on retries / fix loops.
        return code

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pattern_line = f"-- Pattern  : {pattern}" if pattern else None
    domain_line = f"-- Domain   : {domain}" if domain else None
    module_line = f"-- Module   : {module_name}" if module_name else None

    lines = [
        "-- =============================================================",
        f"-- {_HEADER_MARKER}  \u2014  https://canton.ginie.xyz",
        "-- AI-generated DAML for Canton Network. Review before deploying",
        "-- to a production node.",
    ]
    meta = [ln for ln in (pattern_line, domain_line, module_line) if ln]
    if meta:
        lines.append("--")
        lines.extend(meta)
    lines.append(f"-- Generated: {ts}")
    lines.append("-- =============================================================")
    lines.append("")  # blank line before module header

    return "\n".join(lines) + "\n" + code.lstrip()
